config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, controllers: { sessions: 'sessions' }

  resources :employees do
    resources :attendances, except: [:show, :destroy]
  end

  resources :events do
    collection do
      get :home
    end
  end

  resources :departments do
    resources :teams
    resources :projects do
      resources :tasks do
        member do
          get 'edit_status'
          patch 'update_status'
        end
      end
    end
  end

  resources :tasks, only: [:employee_tasks, :update_task_logtime]
  resources :settings, except: [:new, :create, :show, :destroy]

  get 'menus/index' => 'menus#index'
  get 'menus/home' => 'menus#home'
  post 'menus/home' => 'menus#home'
  get 'menus/search_email' => 'menus#search_email'
  root 'menus#home'

  get 'reports/velocity' => 'reports#show', as: :show_employee_velocity_report
  get 'reports/export_report' => 'reports#pdf_velocity_report', as: :pdf_velocity_report
  get 'reports/single_team_tasks' => 'reports#single_team_tasks',as: :single_team_tasks_report
  get 'employees_attendance_report' => 'reports#attendance_report', as: :attendance_report
  get 'employees_report_pdf' => 'reports#attendance_report_pdf'

  get 'employee_tasks' => 'tasks#employee_tasks', :as => :employee_tasks_list
  patch 'tasks/:id/update_task_logtime' => 'tasks#update_task_logtime', :as => :update_task_logtime
  get 'employee_lists' => 'members#employees_lists'
  resources :members, except: [:show]
  get '/members/show/:sequence_num' => 'members#show', :as => :member_show
  get '/messages/index' => 'messages#index'
  post '/messages/' => 'messages#create'

  get 'employees_attendance_report' => 'reports#attendance_report'
  get 'employees_report_pdf' => 'reports#attendance_report_pdf'

  get '/teams/team_members' => 'teams#team_members'

  get 'employees/:id/projects' => 'projects#index', as: :projects_page

  # get 'employee/attendance' => 'attendances#create', as: :employee_attendance
  # get 'employee/attendance/update' => 'attendances#update', as: :update_attendance
  get 'employee/:employee_id/my_attendance' => 'attendances#show_employee_attendance', as: :show_employee_attendance

  resources :reports do
    collection do
      get 'load_task_data_in_report' => 'reports#load_task_data_in_report'
      get 'task_report' => 'reports#task_report'
      get 'task_pdf_csv_report' => 'reports#task_pdf_csv_report'
    end
  end
  get 'teamslist' => 'teams#teams_list'

  get '404', to: 'menus#page_not_found'
end

app/models/task.rb
class Task < ActiveRecord::Base
  not_multitenant!
  EMPLOYEE = 'Employee'.freeze
  TEAM     = 'Team'.freeze
  NEW_STATUS = 'New'.freeze
  ASSIGNED_STATUS = 'Assigned'.freeze
  IN_PROGRESS = 'In Progress'.freeze
  READY_TO_REVIEW = 'Ready to Review'.freeze
  REVIEW_COMPLETED = 'Review Completed'.freeze
  UNASSIGNED_STATUS = 'unassigned'.freeze
  STATUS = [1..10].freeze
  COMPLEXITY = (1..10).freeze
  belongs_to :company
  belongs_to :project
  belongs_to :assignable, polymorphic: true
  validates :start_date, :expected_end_date, :name, :company_id, :project_id, presence: :true
  validate :check_start_date, on: :create
  validate :check_start_and_end_date
  has_many :task_time_logs, dependent: :destroy
  validates :complexity, inclusion: { in: COMPLEXITY }, numericality: true
  belongs_to :reviewer, foreign_key: :reviewer_id, class_name: EMPLOYEE
  scope :get_tasks, ->(user) { where('company_id = ? AND ((tasks.assignable_id in (?) AND tasks.assignable_type = ?) OR (tasks.assignable_id in (?) AND tasks.assignable_type = ?))', user.company_id, Employee.all.team_employees_projects_tasks(user).pluck(:id), EMPLOYEE, user.employee_teams.pluck(:team_id), TEAM) }
  scope :get_employee_tasks, ->(user) { where('company_id = ? AND ((tasks.assignable_id in (?) AND tasks.assignable_type = ?) OR (tasks.assignable_id in (?) AND tasks.assignable_type = ?))', user.company_id, user.id, EMPLOYEE, user.employee_teams.pluck(:team_id), TEAM) }

  def check_start_and_end_date
    errors.add(:expected_end_date, I18n.t('models.task_project.end_date_valid')) if expected_end_date.present? && start_date.present? && expected_end_date.to_date < start_date.to_date
  end

  def check_start_date
    errors.add(:start_date, I18n.t('models.task_project.start_date_valid')) if start_date.present? && start_date.to_date < Date.today
  end

  def get_employees(assignable_type, assignable_id)
    if assignable_type == EMPLOYEE
      company.employees.where(id: assignable_id)
    else
      company.teams.find(assignable_id).employees
    end
  end

  def self.add_email_deliver(id)
    find(id).add_email_deliver
  end

  def add_email_deliver
    employees = get_employees(self.assignable_type, self.assignable_id)
    employees.each do |employee|
      TaskMailer.assign_task_notify(employee, self).deliver
    end
  end

  def self.update_email_deliver(id, assignable_id, assignable_type, task_status)
    find(id).update_email_deliver(assignable_id, assignable_type, task_status)
  end

  def update_email_deliver(assignable_id, assignable_type, task_status)
    unless assignable_id == self.assignable_id
      previous_employees = get_employees(assignable_type, assignable_id)
      employees = get_employees(self.assignable_type, self.assignable_id)
      employees.each do |employee|
        TaskMailer.assign_task_notify(employee, self).deliver
      end
      previous_employees.each do |previous_employee|
        TaskMailer.unassign_task_notify(previous_employee, self).deliver
      end
    end
    unless task_status == self.status
      employees = get_employees(self.assignable_type, self.assignable_id)
      employees.each do |employee|
        TaskMailer.change_task_status_notify(employee, self).deliver
      end
    end
  end
  def set_status
    return self.status = Task::ASSIGNED_STATUS unless assignable_id.blank?
    self.status = Task::NEW_STATUS
    self.assignable_type = nil
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_and_authorize_resource only: [:employee_tasks, :update_task_logtime]
  load_and_authorize_resource :department
  load_and_authorize_resource :project, through: :department, except: [:employee_tasks, :update_task_logtime]
  load_and_authorize_resource :task, through: :project, except: [:employee_tasks, :update_task_logtime]

  # get /departments/:department_id/projects/:project_id/tasks
  def index
    if params[:show_employees_only].present? && current_employee.role != Employee::ADMIN_ROLE
      @tasks = @tasks.get_employee_tasks(current_employee)
    end
    @tasks = @tasks.paginate(page: params[:page], per_page: 5)
    respond_to do |format|
      format.html
    end
  end

  # post /departments/:department_id/projects/:project_id/tasks
  def create
    @task.set_status
    if @task.save
      if @task.assignable_type == Task::EMPLOYEE
        @task.task_time_logs.create(employee_id: @task.assignable_id)
      elsif @task.assignable_type == Task::TEAM
        @task.assignable.employees.each do |employee|
          @task.task_time_logs.create(employee_id: employee.id)
        end
      end
      flash[:success] = t('.success_notice')
      redirect_to department_project_tasks_path
    else
      render :new
    end
  end

  # patch /departments/:department_id/projects/:project_id/tasks/:id
  def update
    if params[:assignable_employee_id].present? && params[:assignable_team_id].present?
      flash[:danger] = t('.error_field_notice')
      render :edit
    else
      params[:task][:status] = Task::NEW_STATUS if !params[:task][:assignable_id].present?
      params[:task][:status] = Task::ASSIGNED_STATUS if params[:task][:assignable_id].present?
      if @task.update(task_params)
        flash[:success] = t('.success_notice')
        redirect_to department_project_tasks_path
      else
        rrender :new
      end
    end
  end

  # delete /departments/:department_id/projects/:project_id/tasks/:id
  def destroy
    @task.destroy
    if @task.destroyed?
      flash[:success] = t('.success_notice')
    else
      flash[:danger] = t('.error_notice')
    end
    redirect_to department_project_tasks_path
  end

  # patch /departments/:department_id/projects/:project_id/tasks/:id/update_status
  def update_status
    if @task.update_attribute('status', task_params[:status])
      flash[:success] = t('.success_notice')
    else
      flash[:danger] = t('.error_notice')
    end
    redirect_to department_project_tasks_path
  end

  # patch /tasks/:id/update_task_logtime
  def update_task_logtime
    unless params[:task_time_log][:hours].blank?
      @task_log = @task.task_time_logs.find_by(employee_id: current_employee.id, task_id: @task.id)
      @result = @task_log.
        update_attribute('hours', @task_log.hours.to_i + params[:task_time_log][:hours].to_i)
      if @result
        flash.now[:success] = t('.success_notice')
      else
        flash.now[:danger] = t('.error_notice')
      end
    end
    respond_to do |format|
      format.js
    end
  end

  private

  def task_params
    params.require(:task).
      permit(:company_id, :start_date, :expected_end_date, :description, :name, :project_id, :status, :assignable_type, :assignable_id, :complexity, :reviewer_id)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def set_assignable_hash(task, assignable_type)
    return nil if task.assignable_type.nil?
    return [task.assignable].to_json.html_safe if task.assignable_type == assignable_type
  end

  def task_time_logs_form(task)
    task.task_time_logs.where(employee_id: current_employee.id).first
  end

  def get_assignable_name(task)
    return Task::UNASSIGNED_STATUS if task.assignable.nil?
    task.assignable.name.titleize
  end

  def get_assignable_type(task)
    return Task::UNASSIGNED_STATUS if task.assignable.nil?
    task.assignable_type.capitalize
  end

  def task_logtime(task)
    task.task_time_logs.inject(0) { |sum, task_log| sum + task_log.hours.to_i }
  end

  def get_reviewer_hash(task)
    return nil if task.reviewer_id.nil?
    return [task.reviewer].to_json.html_safe
  end

  def get_time_logs(task)
    task.task_time_logs
  end

  def log_by_employee(log)
    log.company.employees.find_by(log.employee_id).name
  end

  def task_status_percentage(task)
    if task.status == Task::NEW_STATUS
      return 10
    elsif task.status == Task::ASSIGNED_STATUS
      return 20
    elsif task.status == Task::IN_PROGRESS
      return 60
    elsif task.status == Task::READY_TO_REVIEW
      return 80
    elsif task.status == Task::REVIEW_COMPLETED
      return 100
    end
  end

  def task_time_logs_form(task)
    task.task_time_logs.where(employee_id: current_employee.id).first
  end
end

app/views/tasks/_employee.html.erb
<% assignable_employee_hash = set_assignable_hash(@task,Employee::EMPLOYEE_ROLE) %>
<%= text_field_tag :assignable_employee_id, assignable_employee_hash, class: "js-assign-employee" %>
<%= javascript_tag do %>
$('.js-assign-employee').tokenInput('/employee_lists.json', { prePopulate: <%= assignable_employee_hash %>, tokenLimit: 1 });
<% end %>

app/views/tasks/_form.html.erb
<%= form_for [@department, @project, @task] do |form| %>

  <%= render partial: 'hidden', locals: { form: form } %>
  <div class="container">
    <div class="row d-flex justify-content-start">
      <div class="form-group col-md-6 add_someone">
        <% if @task.assignable_type.nil? || @task.assignable_type == Employee::EMPLOYEE_ROLE %>
          <label class="col pl-1">
            <input type="radio" name="adding"; value="1" checked="checked" class="js-toggle-team-employee-input-token" data-type="Employee">
            Add a task for Employee
          </label>
          <div class= "adding_employee_field js-toggleable-input-token">
             <%= render partial: 'employee', locals: { form: form } %>
          </div>
          <label class="col pl-1">
            <input type="radio" name="adding"; value="2" class="js-toggle-team-employee-input-token team_radio"  data-type="Team"/>
            Add a task for Team
          </label>
          <div class= "adding_team_field collapse js-toggleable-input-token">
             <%= render partial: 'team', locals: { form: form } %>
          </div>
        <% else %>
          <label class="col pl-1">
            <input type="radio" name="adding"; value="1" class="js-toggle-team-employee-input-token team_radio" data-type="Employee">
            Add a task for Employee
          </label>
          <div class= "adding_employee_field collapse js-toggleable-input-token">
             <%= render partial: 'employee', locals: { form: form } %>
          </div>
          <label class="col pl-1">
            <input type="radio" name="adding"; value="2" checked="checked" class="js-toggle-team-employee-input-token"  data-type="Team"/>
            Add a task for Team
          </label>
          <div class= "adding_team_field js-toggleable-input-token">
             <%= render partial: 'team', locals: { form: form } %>
          </div>

        <% end %>
        <small id="emailHelp" class="form-text text-muted">You can choose to not assign task right now.</small>
      </div>
      <div class="form-group col-md-6">
        <div class= "adding_reviewer_field">
         <%= render partial: 'reviewer', locals: { form: form } %>
      </div>
      </div>
    </div>
  </div>

  <br>
  <div class="container">
    <div class="actions">
      <%= link_to request.env["HTTP_REFERER"], :class => "btn btn-regular" do %>
        <i class="fas fa-arrow-left"></i>
      <% end %>
      <%= form.submit class: "btn btn-regular submit_form"  %>
    </div>
  </div>

</div>

<% end %>

app/views/tasks/_reviewer.html.erb
<%= form.label :reviwer_id, "Reviewer Email" %><br>
<% assign_reviewer_hash = get_reviewer_hash(@task) %>
<%= form.text_field :reviewer_id, value: assign_reviewer_hash, class: "js-assign-reviewer" %>
<%= javascript_tag do %>
$('.js-assign-reviewer').tokenInput('/employee_lists.json', { prePopulate: <%= assign_reviewer_hash %>, tokenLimit: 1 });
<% end %>

app/views/tasks/_task_progress.html.erb
<div class="row d-flex">
  <div class="col-12">
    <div class="task-progress">
      <div class="progress custom-progress">
        <% if @task.status == Task::NEW_STATUS %>

        <% elsif @task.status == Task::ASSIGNED_STATUS %>
          <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%"></div>
        <% end %>
        
      </div>
    </div>
  </div>
</div>

app/views/tasks/_taskgrid.html.erb
<% if !@tasks.empty? %> 
<table id="taskgrid_table" class="table data table-hover dt-responsive full-width">
  <thead>
    <tr>
      <th >NAME</th>
      <th >ASSIGNED TO</th>
      <th >START DATE</th>
      <th >EXPECTED END DATE</th>
      <th >STATUS</th>
      <th >ACTIONS</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td class="clickable-item"><%= link_to task.name.downcase.titleize, department_project_task_path(@department, @project,task) %></td>
      <td><%= get_assignable_name(task) %></td>
      <td ><%= task.start_date.strftime("%B %e, %Y") %></td>
      <td ><%= task.expected_end_date.strftime("%B %e, %Y") %></td>
        <td><span class="badge badge-success"><%= task.status.downcase %></span></td>
      <td  class="d-table-cell align-middle vertical-align">
        <div class="row no-gutters justify-content-between">
          <div class="actions">
            <%= link_to department_project_task_path(@department, @project,task) do %>
            <i title="Show Tasks" class="table-options action-show fas fa-eye"></i>
            <% end %>
            <% if can? :create, task %>
            <%= link_to edit_department_project_task_path(@department, @project, task) do %>
            <i title="Edit Task" class="table-options action-edit fas fa-edit"></i>
            <% end %>
            <%= link_to department_project_task_path(@department, @project,task), method: :delete, data: { confirm: 'Are you sure?' } do %> 
            <i title="Delete Task" class="table-options action-delete fas fa-trash"></i>
            <% end %>
            <% end %>
          </div>
          <div class="btn-group dropleft">
            <i class="fas fa-ellipsis-v" title="More..." style="cursor:pointer;font-size:16px" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ></i>
            <div class="dropdown-menu">
              <%= link_to 'Change Status', '#', { class: "dropdown-item", 'data-toggle' => 'modal',  'data-target' => '#taskStatusModal_'+task.id.to_s} %>
            </div>
          </div>
                        <div class="modal fade" id="taskStatusModal_<%=task.id%>" tabindex="-1" role="dialog" aria-labelledby="taskStatusModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="taskStatusModalLabel">Change Task Status</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <div>
                        <strong>Task Title:</strong>
                        <%= task.name.titleize %>
                      </div><br>
                      <div>
                        <%= form_for task, url: update_status_department_project_task_path(@department, @project,task) do |form| %>
                        <%= form.select(:status, ["In Progress","Ready to Review", "Review Completed"], {}, {class: 'form-control'}) %>
                      </div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                      <%= form.submit class: "btn btn-regular" %>
                      <%end%>
                    </div>
                  </div>
                </div>
              </div>

        </div>
      </td>
    </tr>

    <% end %>
  </tbody>
</table>             
<% end %>
<div class="pagination-div">
<%= will_paginate @tasks, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
</div>

app/views/tasks/_team.html.erb
<% assignable_team_hash = set_assignable_hash(@task,Employee::TEAM_ROLE) %>
<%= text_field_tag :assignable_team_id, assignable_team_hash, class: "js-assign-team" %>
<%= javascript_tag do %>
$('.js-assign-team').tokenInput('/teamslist.json', { prePopulate: <%= assignable_team_hash %>, tokenLimit: 1 });
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/employee_tasks.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'employee_tasks' %>
<% end %>

<div class="container" id="tasks_table_1">
  <table id="tasks_table" class="table table-striped table-bordered" style="width:100%">
  <thead>
    <tr>
      <th>Task Name</th>
      <th>Status</th>
      <th>Task Complexity</th>
      <th>Expected End Date</th>
      <th>Hours Worked</th>
      <th>Add logtime</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td>
        <%= task.name %>
      </td>
      <td>
        <%= task.status %>
      </td>
      <td>
        <%= task.complexity %>
      </td>
      <td>
        <%= task.expected_end_date.to_formatted_s(:short) %>
      </td>
      <td>
        <%= task_logtime(task) %>
      </td>
      <td>
        <%= form_for task_time_logs_form(task), url: update_task_logtime_path(task), remote: true, html: { method: :patch } do |form|%>
        <div class="row">
          <div class="col-md">
            <%= form.text_field :hours , class: 'form-control' %>
          </div>
          <div class="col-md">
            <%= form.submit 'Submit log-time', class: 'btn btn-regular', id: task.name+"_submit", data: { "disable-with" => "wait"} %>
          </div>
        </div>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/tasks/index.html.erb
<% content_for :bread_crumbs do %>
  <div class="row d-flex p-1">
      <p class="m-0 align-middle"><%= link_to "#{@project.department.name.titleize}", department_path(@department), class: 
    'text-prim no-decoration' %> > <%= @project.name.titleize %> > Tasks</p>
      <div class="m-0 pl-2">
        <%= link_to department_projects_path(@department), :class => "btn btn-regular btn-circle btn-md" do %>
          <i class="fas fa-arrow-left"></i>
        <% end %>
        <% if can? :create, Task %>
          <%= link_to new_department_project_task_path(@department, @project), :class => "btn btn-regular btn-circle btn-md" do %>
            <i class="fas fa-plus"></i>
          <% end %>
        <% else %>
            <%= link_to "All Tasks", department_project_tasks_path(@department, @project), remote: true, class: "btn btn-regular active"%>
            <%= link_to "My Tasks", department_project_tasks_path(@department, @project, show_employees_only: true), remote: true, class: "btn btn-regular" %>
        <% end %>
      </div> 
  </div>
<% end %>

<div class="container">
  <div class="card">
    <div class="card-header">
      <h5>Project: <b><%= @project.name.titleize %></b></h5>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col">
          <h6><b>Department: </b><%= @project.department.name.titleize %></h6>
        </div>
        <div class="col">
          <h6><b>Status: </b><%= @project.status %></h6>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <h6><b>Start date: </b><%= @project.start_date.to_date %></h6>
        </div>
        <div class="col">
          <h6><b>Expected end date: </b><%= @project.expected_end_date.to_date %></h6>
        </div>
      </div>
    </div>
  </div>

<br>
<div id="tasks_grid" class="mt-3">
  <%= render partial: 'taskgrid', locals: {tasks: @tasks}  %>
</div>
<% if @project.tasks.empty? %>
  <p id="notice"><i>No Records Found.</i></p>
<% end %>
</div>

app/views/tasks/index.js.erb
$("#tasks_grid").html("<%= escape_javascript(render partial: 'taskgrid', locals: { tasks: @tasks } ) %>"); 

app/views/tasks/show.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'task_show' %>
<% end %>

<% content_for :bread_crumbs do %>
  <div class="row d-flex p-1">
      <p class="m-0 align-middle"><%= link_to "#{@task.project.department.name.titleize}", department_path(@department), class: 
    'text-prim no-decoration' %> > <%= link_to "#{@task.project.name.titleize}", department_project_tasks_path(@department,@project), class: 
    'text-prim no-decoration' %> > <%= @task.name.downcase.titleize %> > Task Details</p>
      <div class="m-0 pl-2">
        <%= link_to department_project_tasks_path(@department,@project), :class => "btn btn-regular btn-circle btn-md" do %>
          <i class="fas fa-arrow-left"></i>
        <% end %>
        <% if can? :create, Task %>
          <%= link_to edit_department_project_task_path(@department, @project, @task), :class => "btn btn-peach btn-circle btn-md" do %>
            <i class="fas fa-edit"></i>
          <% end %>
          <%= link_to department_project_task_path(@department, @project, @task), method: :delete, data: { confirm: 'Are you sure?' }, remote: :true, class: "btn btn-outline-danger btn-circle btn-md" do %>
            <i class="fas fa-trash"></i>
          <% end %>
        </div>
      <% end %>
  </div>
<% end %>

<div class="container task-show-div" id="task_show_container">
  <div class="row d-flex">
    <div class="col-8">
        <h2 class="text-prim"><b><%= @task.name.downcase.titleize %></b></h2>
      <br>
      <div class="row d-flex">
        <div class="col-12">
          <p class="text-second">Task Status: <span class="text-peach"><%=@task.status.downcase.titleize%></span></p>
        </div>
      </div>
      <div class="row d-flex">
        <div class="col-12">
          <div class="task-progress">
            <input type="hidden" id="taskId" name="taskId" value="<%=task_status_percentage(@task)%>">
            <div class="progress active" id="progressBar" data-toggle="popover" title="Task Status: <%=@task.status%>">
              <div class="progress-bar progress-bar-animated" id="task_progress_bar" role="progressbar"  aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%"></div>
            </div>
          </div>
        </div>
      </div>
      <br>
    </div>
    <div class="col-4">
      <div class="rounded-complexity">
        <center>
        <%= image_tag('ai-secondary.svg', size: "30x30")%><br>
        <span class="text-prim">Complexity <%= @task.complexity%></span>
      </center>
      </div>
    </div>
  </div><br><br>
  
  <div class="row d-flex">
    <div class="col-4">
      <center>
        <%= image_tag('work-secondary.svg', size: "80x80")%><br>
        <span class="text-peach">
          <% if @task.assignable_type == Task::TEAM %>
          <%= link_to @task.assignable.name, department_team_path(@department, @task.assignable) , class: 'text-peach no-decoration' %>
          <% elsif @task.assignable_type == Task::EMPLOYEE %>
          <%= link_to @task.assignable.name, member_show_path(@task.assignable), class: 'text-peach no-decoration' %>
          <% end %>
           is working on this task.</span>
      </center>
    </div>
    <div class="col-4">
      <center>
        <%= image_tag('customer-review-secondary.svg', size: "80x80")%><br>
        <% if !@task.reviewer.nil? %>
        <span class="text-peach"><%= link_to @task.reviewer.name.downcase.titleize, member_show_path(@task.reviewer), class: 'text-peach no-decoration' %> is reviewing this task.</span>
        <% else %>
        <span class="text-peach"><i>No one</i> is reviewing this task.</span>
        <% end %>
      </center>
    </div>
    <div class="col-4">
      <div class="table-details task-times">
        <div class="detail-head-task"></div>
        <table class="table borderless">
          <tr>
            <td class="text-prim"><i class="fas fa-clock"></i><b> Start Date:</b></td>
            <td class="text-peach"><%= @task.start_date.to_date %></td>
          </tr>
          <tr>
            <td class="text-prim"><i class="fas fa-stopwatch"></i><b> End Date:</b></td>
            <td class="text-peach"><%= @task.expected_end_date.to_date %></td>
          </tr>
        </table>
      </div>
    </div>
  </div>
  <br><br>
  <div class="row d-flex lower-half-task-show task-logs">
      <div class="col-6">
        <div class="show-col-left">
          <% @time_logs = get_time_logs(@task) %>
          <span class="text-prim"><h5><b>Time Logs for this task</b></h5></span>
          <% if @time_logs.any? %>
            <table class="table table-hover text-second">
              <thead>
                <tr>
                  <th>Day</th>
                  <th>Time Logged</th>
                  <% if @task.assignable_type == Task::TEAM %>
                    <th>Logger</th>
                  <% end %>
                </tr>
              </thead>
              <tbody class="scroll-able text-peach">
                
                <% @time_logs.each do |log| %>
                  <tr>
                    <td class="text-second"><%= log.created_at.to_formatted_s(:short) %></td>
                    <td class="text-second"><% if log.hours.blank? %> - <% else %>
                      <%= log.hours.to_formatted_s(:short).to_i %> hours
                      <% end %>
                    </td>
                    <% if @task.assignable_type == Task::TEAM %>
                      <td><%= link_to log.employee.name.downcase.titleize , member_show_path(log.employee), class: 'text-peach no-decoration' %></td>
                    <% end %>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <%else%>
            <span class="text-second"><h5><i>No Time Logs found.</i></h5></span>
          <%end%>
        </div>
      </div>
      <div class="col-6">
        <div class="show-col-right">
          <span class="text-prim"><h5><b>Learn More about this task</b></h5></span>
          <div class="card">
            <div class="card-body" id="collapseCardDescription">
              <span class="text-peach">
                <%if @task.description.blank?%>
                  <i>*no description provided*</i> 
                <% else %>
                  <%= @task.description %></span>
                <% end %>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>