config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, controllers: { sessions: 'sessions' }

  resources :employees do
    resources :attendances, except: [:show, :destroy]
  end

  resources :events do
    collection do
      get :home
    end
  end

  resources :departments do
    resources :teams
    resources :projects do
      resources :tasks do
        member do
          get 'edit_status'
          patch 'update_status'
        end
      end
    end
  end

  resources :tasks, only: [:employee_tasks, :update_task_logtime]
  resources :settings, except: [:new, :create, :show, :destroy]

  get 'menus/index' => 'menus#index'
  get 'menus/home' => 'menus#home'
  post 'menus/home' => 'menus#home'
  get 'menus/search_email' => 'menus#search_email'
  root 'menus#home'

  get 'reports/velocity' => 'reports#show', as: :show_employee_velocity_report
  get 'reports/export_report' => 'reports#pdf_velocity_report', as: :pdf_velocity_report
  get 'reports/single_team_tasks' => 'reports#single_team_tasks',as: :single_team_tasks_report
  get 'employees_attendance_report' => 'reports#attendance_report', as: :attendance_report
  get 'employees_report_pdf' => 'reports#attendance_report_pdf'

  get 'employee_tasks' => 'tasks#employee_tasks', :as => :employee_tasks_list
  patch 'tasks/:id/update_task_logtime' => 'tasks#update_task_logtime', :as => :update_task_logtime
  get 'employee_lists' => 'members#employees_lists'
  resources :members, except: [:show]
  get '/members/show/:sequence_num' => 'members#show', :as => :member_show
  get '/messages/index' => 'messages#index'
  post '/messages/' => 'messages#create'

  get 'employees_attendance_report' => 'reports#attendance_report'
  get 'employees_report_pdf' => 'reports#attendance_report_pdf'

  get '/teams/team_members' => 'teams#team_members'

  get 'employees/:id/projects' => 'projects#index', as: :projects_page

  # get 'employee/attendance' => 'attendances#create', as: :employee_attendance
  # get 'employee/attendance/update' => 'attendances#update', as: :update_attendance
  get 'employee/:employee_id/my_attendance' => 'attendances#show_employee_attendance', as: :show_employee_attendance

  resources :reports do
    collection do
      get 'load_task_data_in_report' => 'reports#load_task_data_in_report'
      get 'task_report' => 'reports#task_report'
      get 'task_pdf_csv_report' => 'reports#task_pdf_csv_report'
    end
  end
  get 'teamslist' => 'teams#teams_list'

  get '404', to: 'menus#page_not_found'
end

app/models/project.rb
class Project < ActiveRecord::Base
  not_multitenant!
  NEW_STATUS = 'new'.freeze
  belongs_to :department
  belongs_to :company
  has_many :tasks, dependent: :destroy
  validates :start_date, :expected_end_date, :name, :department_id, presence: :true
  validate :check_start_date, on: :create
  validate :check_start_and_end_date
  scope :get_projects, ->(user) { joins(tasks: :project).where(tasks: { id: Task.all.get_tasks(user), company_id: user.company_id }).distinct }
  scope :employee_projects, ->(user) { joins(tasks: :project).where(tasks: { id: Task.all.employee_tasks(user), company_id: user.company_id }).distinct }

  def check_start_and_end_date
    errors.add(:expected_end_date, I18n.t('models.task_project.end_date_valid')) if expected_end_date.present? && start_date.present? && expected_end_date.to_date < start_date.to_date
  end

  def check_start_date
    errors.add(:start_date, I18n.t('models.task_project.start_date_valid')) if start_date.present? && start_date.to_date < Date.today
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource :department
  load_and_authorize_resource through: :department

  # get /departments/:department_id/projects
  def index
    if params[:show_employees_only].present? && current_employee.role != Employee::ADMIN_ROLE
      @projects = @projects.employee_projects(current_employee)
    end
    @projects = @projects.paginate(page: params[:page], per_page: 5)
    respond_to do |format|
      format.html
    end
  end

  # post /departments/:department_id/projects
  def create
    @project.status = Project::NEW_STATUS
    respond_to do |format|
      if @project.save
        format.html do
          flash[:success] = t('.success_notice', project_name: @project.name.downcase.titleize)
          redirect_to department_projects_path
        end
      else
        format.html do
          flash[:danger] = t('.error_notice')
          redirect_to department_projects_path
        end
      end
    end
  end
  # delete /departments/:department_id/projects/:id
  def destroy
    @project.destroy
    respond_to do |format|
      if @project.destroyed?
        format.html do
          flash[:success] = t('.success_notice')
          redirect_to department_projects_path
        end
      else
        format.html do
          flash[:danger] = t('.error_notice')
          redirect_to department_projects_path
        end
      end
    end
  end

  # patch /departments/:department_id/projects/:id
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html do
          flash[:success] = t('.success_notice')
          redirect_to department_projects_path
        end
      else
        format.html do
          flash[:danger] = t('.error_notice')
          redirect_to department_projects_path
        end
      end
    end
  end

  private

  def project_params
    params.require(:project).permit(:description, :name, :start_date, :expected_end_date, :department_id)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for [@department,@project] do |form| %>
<% if @project.errors.any? %>
  <div class="row p-0 ml-1 mr-1">
    <div class="col-1"></div>
    <div class='alert alert-danger col-10' id="flash-alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <div class="mb-0">
        <% @project.errors.full_messages.each do |message| %>
          <div class="p-0"><i class="fa fa-exclamation-circle pr-2"></i><%= message %></div>
        <% end %>
      </div>
    </div>
    <div class="col-1"></div>
  </div>
<% end %>
<div class="row">
  <div class="col-1"></div>
  <div class="col-10">
    <div class="row d-flex justify-content-start">
      <div class="form-group col-12">
        <%= form.label :name %><br>
        <%= form.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="row d-flex justify-content-start">
      <div class="form-group col-12">
        <%= form.label :description %><br>
        <%= form.text_area :description, class: "form-control", placeholder: "Enter description" %>
      </div>
    </div>
    <div class="row d-flex justify-content-start">
      <div class="form-group col-6">
        <%= form.label "Start Date" %><br>
        <%= form.date_field :start_date, class: "form-control" %>
      </div>
      <div class="form-group col-6">
       <%= form.label "Expected End Date" %><br>
       <%= form.date_field :expected_end_date, class: "form-control" %>
     </div>
    </div>
    <div class="actions mt-2">
      <%= link_to request.env["HTTP_REFERER"], :class => "btn btn-regular" do %>
        <i class="fas fa-arrow-left"></i>
      <% end %>
      <%= form.submit class: "btn btn-regular"  %>
    </div>
  </div>
  <div class="col-1"></div>
</div>
<% end %>

app/views/projects/_projectsgrid.html.erb
<div class="container table-responsive">
<table id="project_table" class="table data table-hover dt-responsive full-width">
  <thead>
    <tr>
      <th >NAME</th>
      <th >START DATE</th>
      <th >EXPECTED END DATE</th>
      <th >STATUS</th>
      <th >ACTIONS</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
    <tr>
      <td class="clickable-item"><%= link_to project.name.downcase.titleize, department_project_tasks_path(@department,project) %></td>
      <td ><%= project.start_date.strftime("%B %e, %Y") %></td>
      <td ><%= project.expected_end_date.strftime("%B %e, %Y") %></td>
      <td ><%= project.status %></td>
      <td  class="d-table-cell align-middle vertical-align">
        <div class="row no-gutters justify-content-between">
          <div class="actions">
            <%= link_to department_project_tasks_path(@department,project) do %>
            <i title="Show Tasks" class="table-options action-show fas fa-eye"></i>
            <% end %>
            <% if can? :create, project %>
            <%= link_to edit_department_project_path(@department,project) do %>
            <i title="Edit Project" class="table-options action-edit fas fa-edit"></i>
            <% end %>
            <%= link_to department_project_path(@department,project), method: :delete, data: { confirm: 'Are you sure?' } do %>  
            <i title="Delete Project" class="table-options action-delete fas fa-trash"></i>
            <% end %>
            <% end %>
          </div>
          <div class="btn-group dropleft">
            <i class="fas fa-ellipsis-v cursor-pointer" title="More..." class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ></i>
            <div class="dropdown-menu">
                  <%= link_to "Show Tasks",department_project_tasks_path(project.department,project), class:"dropdown-item" %>
            </div>
          </div>

        </div>
      </td>
    </tr>

    <% end %>
  </tbody>
</table>
</div>
<div class="pagination-div">
<%= will_paginate @projects, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
</div>

app/views/projects/edit.html.erb
<% content_for :bread_crumbs do %>
  <div class="row d-flex p-1">
      <p class="m-0 align-middle"><%= link_to "#{@project.department.name.titleize}", department_path(@project.department), class: 
    'text-prim no-decoration' %> > <%= @project.name.titleize %> > Edit Project</p>
      <div class="m-0 pl-2">
        <%= link_to department_projects_path(@project.department), :class => "btn btn-regular btn-circle btn-md" do %>
          <i class="fas fa-arrow-left"></i>
        <% end %>
      </div>
  </div>
<% end %>

<%= render 'form' %>

app/views/projects/index.html.erb
<% content_for :bread_crumbs do %>
  <div class="row d-flex p-1">
      <p class="m-0 align-middle"><%= link_to "#{@projects.first.department.name.titleize}", department_path(@projects.first.department), class: 
    'text-prim no-decoration' %> > Projects</p>
      <div class="m-0 pl-2">
        <%= link_to request.env["HTTP_REFERER"], :class => "btn btn-regular btn-circle btn-md" do %>
          <i class="fas fa-arrow-left"></i>
        <% end %>
        <% if can? :create, Team %>
          <%= link_to new_department_project_path, class: "btn btn-regular btn-circle btn-md" do %>
            <i class="fa fa-plus"></i>
          <% end %>
        <% else %>
          <%= link_to "All Projects", department_projects_path, remote: true, class: "btn btn-regular active"%>
          <%= link_to "My Projects", department_projects_path(show_employees_only: true), remote: true, class: "btn btn-regular" %>
        <% end %>
      </div>
  </div>
<% end %>

<div class="container">
<% if cannot? :create, Project%>
    <%= link_to "All Projects", department_projects_path, remote: true, class: "btn btn-secondary active"%>
    <%= link_to "My Projects", department_projects_path(show_employees_only: true), remote: true, class: "btn btn-secondary active" %>
<% end %>
<% if @projects.present? %>
  <div id="projects_grid" class="mt-3">
    <%= render partial: 'projectsgrid', locals: {projects: @projects}  %>
  </div>
<% else %>
  <p id="notice"><i>No Records Found.</i></p>
<% end %>
</div>
<br>

app/views/projects/index.js.erb
$("#projects_grid").html("<%= escape_javascript(render partial: 'projectsgrid', locals: { projects: @projects } ) %>"); 

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/show.html.erb
<p>
  <strong>Project Title:</strong>
  <%= @project.name.downcase.titleize %>
</p>
<%= link_to 'Edit', edit_member_path(@employee) %> |
<%= link_to 'Back', request.env["HTTP_REFERER"], class: "btn btn-secondary" %>