config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, controllers: { sessions: 'sessions' }

  resources :employees do
    resources :attendances, except: [:show, :destroy]
  end

  resources :events do
    collection do
      get :home
    end
  end

  resources :departments do
    resources :teams
    resources :projects do
      resources :tasks do
        member do
          get 'edit_status'
          patch 'update_status'
        end
      end
    end
  end

  resources :tasks, only: [:employee_tasks, :update_task_logtime]
  resources :settings, except: [:new, :create, :show, :destroy]

  get 'menus/index' => 'menus#index'
  get 'menus/home' => 'menus#home'
  post 'menus/home' => 'menus#home'
  get 'menus/search_email' => 'menus#search_email'
  root 'menus#home'

  get 'reports/velocity' => 'reports#show', as: :show_employee_velocity_report
  get 'reports/export_report' => 'reports#pdf_velocity_report', as: :pdf_velocity_report
  get 'reports/single_team_tasks' => 'reports#single_team_tasks',as: :single_team_tasks_report
  get 'employees_attendance_report' => 'reports#attendance_report', as: :attendance_report
  get 'employees_report_pdf' => 'reports#attendance_report_pdf'

  get 'employee_tasks' => 'tasks#employee_tasks', :as => :employee_tasks_list
  patch 'tasks/:id/update_task_logtime' => 'tasks#update_task_logtime', :as => :update_task_logtime
  get 'employee_lists' => 'members#employees_lists'
  resources :members, except: [:show]
  get '/members/show/:sequence_num' => 'members#show', :as => :member_show
  get '/messages/index' => 'messages#index'
  post '/messages/' => 'messages#create'

  get 'employees_attendance_report' => 'reports#attendance_report'
  get 'employees_report_pdf' => 'reports#attendance_report_pdf'

  get '/teams/team_members' => 'teams#team_members'

  get 'employees/:id/projects' => 'projects#index', as: :projects_page

  # get 'employee/attendance' => 'attendances#create', as: :employee_attendance
  # get 'employee/attendance/update' => 'attendances#update', as: :update_attendance
  get 'employee/:employee_id/my_attendance' => 'attendances#show_employee_attendance', as: :show_employee_attendance

  resources :reports do
    collection do
      get 'load_task_data_in_report' => 'reports#load_task_data_in_report'
      get 'task_report' => 'reports#task_report'
      get 'task_pdf_csv_report' => 'reports#task_pdf_csv_report'
    end
  end
  get 'teamslist' => 'teams#teams_list'

  get '404', to: 'menus#page_not_found'
end

app/models/report.rb
require 'csv'
class Report
  def self.to_csv(tasks)
    options = {}
    header = ['Project Name', 'Task Name', 'Start Date', 'End Date',
              'Assigned To', 'Assigned Type', 'Status']
    CSV.generate(options) do |csv|
      csv << header
      tasks.each do |task|
        csv << [task.project.name, task.name, task.start_date.to_date, task.expected_end_date.to_date,
                task.assignable.name, task.assignable_type, task.status]
      end
    end
  end
  def self.compute_one_employee_velocity(employee_id, tasks_list)
    @total_time_on_tasks = time_spent_on_tasks(employee_id, tasks_list).to_i
    @total_task_complexity = compute_total_complexity_of_tasks(tasks_list).to_i
    (@total_task_complexity.to_f / @total_time_on_tasks)
  end

  def self.compute_total_complexity_of_tasks(employee_tasks)
    return 0 if employee_tasks.blank?

    employee_tasks.inject(0) { |sum, task| sum + task.complexity }
  end

  def self.time_spent_on_tasks(employee_id, employee_tasks)
    return 0 if employee_tasks.blank?

    @sum = 0
    employee_tasks.each do |task|
      @task_log = task.task_time_logs.where(employee_id: employee_id)
      unless @task_log.blank?
        @sum += @task_log.inject(0) { |log_sum, task_log| log_sum + task_log.hours.to_i }
      end
    end
    @sum
  end

  def self.compute_employees_velocity(current_employee)
    if current_employee.role == Employee::EMPLOYEE_ROLE
      @employee_teams = current_employee.teams
    elsif current_employee.role == Employee::ADMIN_ROLE
      @employee_teams = current_employee.company.teams
    end

    @employee_tasks_data = {}

    @employee_teams.each do |team|
      @employees_list = team.employees
      @employee_tasks_data[team.id] = {}
      @employees_list.each do |employee|
        @employee_tasks = employee.company.tasks.get_employee_tasks(employee)
        @employee_tasks_data[team.id][employee.id] = {
          employee_id: employee.id,
          employee_name: employee.name,
          total_tasks: @employee_tasks.count,
          total_time: time_spent_on_tasks(employee.id, @employee_tasks),
          total_complexity: compute_total_complexity_of_tasks(@employee_tasks),
          velocity: compute_one_employee_velocity(employee.id, @employee_tasks)
        }
      end
    end
    @employee_tasks_data
  end

  def self.single_team_velocity(current_employee, team_id)
    if current_employee.role == Employee::EMPLOYEE_ROLE
      @employee_teams = current_employee.teams.find(team_id)
    elsif current_employee.role == Employee::ADMIN_ROLE
      @employee_teams = current_employee.company.teams.find(team_id)
    end

    @employee_tasks_data = {}
    team = @employee_teams
    @employees_list = team.employees
    # @employee_tasks_data[team.id] = {}
    @employees_list.each do |employee|
      @employee_tasks = employee.company.tasks.get_employee_tasks(employee)
      @employee_tasks_data[employee.id] = {
        employee_id: employee.id,
        employee_name: employee.name,
        total_tasks: @employee_tasks.count,
        total_time: time_spent_on_tasks(employee.id, @employee_tasks),
        total_complexity: compute_total_complexity_of_tasks(@employee_tasks),
        velocity: compute_one_employee_velocity(employee.id, @employee_tasks)
      }
    end
    @employee_tasks_data
  end

  def self.attendance_data(current_employee, all_employees = true)
    attendances_array = []
    holidays = []
    current_employee.company.setting.holidays.each do |index, date|
      holidays << date["holiday_date_#{index}"]
    end

    if all_employees
      current_employee.company.employees.each do |employee|
        @attendances = employee.attendances.where(status: Attendance::STATUS[:PRESENT]).order(login_time: :asc).select { |attendance| attendance.login_time.year == Date.today.year && attendance.logout_time != nil }
        if !@attendances.empty?
          full_days, half_days, absents, leaves_remaining = attendance_details(@attendances, holidays, current_employee)
          attendances_array << {
            employee: employee,
            presents: full_days,
            half_days: half_days,
            absents: absents,
            leaves_remaining: leaves_remaining
          }
        end
      end
      return attendances_array
    else
      @attendances = current_employee.attendances.where(status: Attendance::STATUS[:PRESENT]).order(login_time: :asc).select { |attendance| attendance.login_time.year == Date.today.year && attendance.logout_time != nil }
      if !@attendances.empty?
        full_days, half_days, absents, leaves_remaining = attendance_details(@attendances, holidays, current_employee)
        return leaves_remaining
      end
      return 0
    end
  end

  def self.attendance_details(attendances, holidays, current_employee)
    end_date = "31-12-#{Date.today.year}".to_date
    week_days = [1, 2, 3, 4, 5]
    first_attendance_date = attendances.first.login_time.to_date
    last_attendance_date = attendances.last.login_time.to_date
    public_holidays = holidays.select {|date| date.to_date > first_attendance_date && date.to_date < last_attendance_date}.count
    expected_working_days = (first_attendance_date..last_attendance_date).to_a.select { |k| week_days.include?(k.wday) }.count - public_holidays
    leaves = (end_date.month - first_attendance_date.month + 1) * (current_employee.company.setting.allocated_leaves / 12 )
    actual_working_days = attendances.count
    half_days = attendances.select { |attendance| ((attendance.logout_time - attendance.login_time) / 3600) <= 6 }.count
    full_days = actual_working_days - half_days
    absents = expected_working_days - actual_working_days
    return full_days, half_days, absents, (leaves - absents - (half_days / 2).floor)
  end

  def self.get_task_query_hash(param_project, status, created_start, created_end, deadline_start, deadline_end)
    task_query_hash = {}
    unless param_project.empty?
      project = Project.find_by(name: param_project)
      unless project.blank?
        task_query_hash[:project_id] = project.id
      else
        task_query_hash[:project_id] = ''
      end
    end
    unless status.empty?
      task_query_hash[:status] = status
    end
    if !created_start.empty? || !created_end.empty?
      if created_start.empty?
        task_query_hash[:start_date] = Time.zone.parse(created_end)
      elsif created_end.empty?
        task_query_hash[:start_date] = Time.zone.parse(created_start)
      else
        task_query_hash[:start_date] = Time.zone.parse(created_start)..Time.zone.parse(created_end)
      end
    end
    if !deadline_start.empty? || !deadline_end.empty?
      if deadline_start.empty?
        task_query_hash[:expected_end_date] = Time.zone.parse(deadline_end)
      elsif deadline_end.empty?
        task_query_hash[:expected_end_date] = Time.zone.parse(deadline_start)
      else
        task_query_hash[:expected_end_date] = Time.zone.parse(deadline_start)..Time.zone.parse(deadline_end)
      end
    end
    task_query_hash
  end

  def self.get_task_query_hash(param_project, status, created_start, created_end, deadline_start, deadline_end)
    task_query_hash = {}
    unless param_project.empty?
      project = Project.find_by(name: param_project)
      unless project.blank?
        task_query_hash[:project_id] = project.id
      else
        task_query_hash[:project_id] = ''
      end
    end
    unless status.empty?
      task_query_hash[:status] = status
    end
    if !created_start.empty? || !created_end.empty?
      if created_start.empty?
        task_query_hash[:start_date] = Time.zone.parse(created_end)
      elsif created_end.empty?
        task_query_hash[:start_date] = Time.zone.parse(created_start)
      else
        task_query_hash[:start_date] = Time.zone.parse(created_start)..Time.zone.parse(created_end)
      end
    end
    if !deadline_start.empty? || !deadline_end.empty?
      if deadline_start.empty?
        task_query_hash[:expected_end_date] = Time.zone.parse(deadline_end)
      elsif deadline_end.empty?
        task_query_hash[:expected_end_date] = Time.zone.parse(deadline_start)
      else
        task_query_hash[:expected_end_date] = Time.zone.parse(deadline_start)..Time.zone.parse(deadline_end)
      end
    end
    task_query_hash
  end
end

app/controllers/reports_controller.rb
require 'date'
class ReportsController < ApplicationController
  protect_from_forgery except: :load_task_data_in_report

  # get /reports/task_report
  def task_report
    @tasks = current_employee.company.tasks.paginate(page: params[:page], per_page: 5)
  end

  # get /reports/load_task_data_in_report
  def load_task_data_in_report
    task_hash = Report.get_task_query_hash(params[:project], params[:status], params[:created_start], params[:created_end], params[:deadline_start], params[:deadline_end])
    @tasks = current_employee.company.tasks.where(task_hash).paginate(page: params[:page], per_page: 10)
    respond_to do |format|
      format.js
    end
  end

  # get /reports/task_pdf_csv_report
  def task_pdf_csv_report
    task_hash = Report.get_task_query_hash(params[:project], params[:status], params[:created_start], params[:created_end], params[:deadline_start], params[:deadline_end])
    @tasks = current_employee.company.tasks.where(task_hash)
    if params[:pdf]
      @pagination_disallow = 0
      request.format = :pdf
    elsif params[:csv]
      request.format = :csv
    end
    respond_to do |format|
      format.csv do
        send_data Report.to_csv(@tasks), filename: "task-#{Time.zone.now.to_datetime}.csv"
      end
      format.pdf do
        render pdf: 'Tasks',
          template: 'reports/task_pdf_report.html.erb',
          layout: 'pdf.html',
          page_size: 'A4',
          dpi: 55
      end
    end
  end

  # get /reports/velocity
  def show
    @employee_tasks_data = Report.compute_employees_velocity(current_employee)
    # @employee_tasks_data = @employee_tasks_data.paginate(page: params[:page], per_page: 5)
  end

  # get /reports/export_report
  def pdf_velocity_report
    @employee_tasks_data = Report.compute_employees_velocity(current_employee)
    respond_to do |format|
      format.pdf do
        render pdf: 'Employees Velocity',
          template: 'reports/employee_velocity_pdf_report.html.erb',
          layout: 'pdf.html',
          page_size: 'A4',
          dpi: 55
      end
    end
  end

  # get /employees_attendance_report
  def attendance_report
    if current_employee.role == Employee::ADMIN_ROLE
      @attendances = Report.attendance_data(current_employee).paginate(page: params[:page], per_page: 10)
    end
  end

  def single_team_tasks
    @team_members_data = Report.single_team_velocity(current_employee,params[:team_id])
    respond_to do |format|
      format.js
    end
  end

  # get /employees_report_pdf
  def attendance_report_pdf
    if current_employee.role == Employee::ADMIN_ROLE
      @attendances = Report.attendance_data(current_employee)
      respond_to do |format|
        format.pdf do
          render pdf: 'Attendance Report',
            template: 'reports/_attendance_report_grid.html.erb',
            layout: 'pdf.html',
            page_size: 'A4',
            dpi: 55
        end
      end
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def employee_velocity(employee_velocity)
    if employee_velocity.to_f.nan? || (employee_velocity == (Float::INFINITY))
      return '-'
    else
      return employee_velocity.round(2)
    end
  end

  def team_name(team_id)
    current_employee.company.teams.find(team_id).name.downcase.titleize
  end

  def team_tasks_count(team_id)
    current_employee.company.teams.find(team_id).tasks.count
  end

  def team_employees_count(team_id)
    current_employee.company.teams.find(team_id).employees.count
  end

  def team_department_name(team_id)
    current_employee.company.teams.find(team_id).department.name.downcase.titleize
  end

end

app/views/reports/_attendance_report_grid.html.erb
<div class="container">
  <div class="row">
    <div class="col-10">
      <center>
        <h1>Employee Attendance Report</h1>
      </center>
    </div>
    <div class="col-2">
      <div class="align-content-right mr-0 pr-0 ml-report-btn">
        <%= link_to  employees_report_pdf_path(format: :pdf), class: 'btn btn-regular', target: :_blank do %>
          Export pdf
          <i class="fas fa-file-pdf ml-2"></i>
        <% end %>
      </div>
    </div>
  </div>
  <center>
    <h1></h1>
  </center>
</div>
<br>
<% if @attendances.any? %>
<div class="container table-responsive">
  <table id="attendancereport_table" class="table data table-hover dt-responsive full-width">
    <thead>
      <tr>
        <th >ID</th>
        <th >NAME</th>
        <th >EMAIL</th>
        <th >PRESENTS</th>
        <th >HALF DAYS</th>
        <th >ABSENTS</th>
        <th >LEAVES REMAINING</th>
      </tr>
    </thead>
    <tbody>
      <% @attendances.each do |attendance|%>
        <tr>
          <td><%= attendance[:employee][:sequence_num] %></td>
          <td><%= attendance[:employee][:name].downcase.capitalize %></td>
          <td><%= attendance[:employee][:email].downcase %></td>
          <td><%= attendance[:presents] %></td>
          <td><%= attendance[:half_days] %></td>
          <td><%= attendance[:absents] %></td>
          <td><%= attendance[:leaves_remaining] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>

app/views/reports/_tasks_report_list.html.erb
<div class="container table-responsive">
<table id="taskdetails_table" class="table data table-hover dt-responsive full-width">
  <thead>
    <tr>
      <th>PROJECT NAME</th>
      <th>TASK NAME</th>
      <th>ASSIGNED TO</th>
      <th>ASSIGNED TYPE</th>
      <th>START DATE</th>
      <th>END DATE</th>
      <th>STATUS</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task|%>
      <tr>
        <td><%= task.project.name.downcase.titleize %></td>
        <td><%= task.name.downcase.titleize %></td>
        <td><%= get_assignable_name(task).downcase.titleize %></td>
        <td><%= get_assignable_type(task) %></td>
        <td><%= task.start_date.strftime("%B %e, %Y") %></td>
        <td><%= task.expected_end_date.strftime("%B %e, %Y") %></td>
        <td><span class="badge badge-success"><%= task.status.downcase %></span></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<% unless @pagination_disallow.present? %>
  <%= will_paginate @tasks, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
<% end %>

app/views/reports/_team_task_velocity.html.erb
<table id="velocityreport_table" class="table data table-hover dt-responsive full-width">
  <thead>
    <tr>
      <th >ID</th>
      <th >NAME</th>
      <th >TOTAL TASKS</th>
      <th >AVG. COMPLEXITY</th>
      <th >AVG. TIME</th>
      <th >VELOCITY <br> (avg. complexity / avg. time)</th>
    </tr>
  </thead>
  <tbody>
      <% @team_members_data.each do |employee_id, employee_velocity_data|  %>
        <tr>
          <td><%= employee_velocity_data[:employee_id] %></td>
          <td><%= employee_velocity_data[:employee_name].downcase.titleize %></td>
          <td><%= employee_velocity_data[:total_tasks] %></td>
          <td><%= employee_velocity_data[:total_complexity] %></td>
          <td><%= employee_velocity_data[:total_time] %></td>
          <td><%= employee_velocity(employee_velocity_data[:velocity]) %></td>
        </tr> 
    <% end %>
  </tbody>
</table>

app/views/reports/_teams_tasks_list.html.erb
<div class="container velocity-report table-responsive">
  <table id="teamstasks_table" class="table data table-hover dt-responsive full-width">
    <thead>
      <tr>
        <th>ID</th>
        <th>NAME</th>
        <th>DEPARTMENT</th>
        <th>NO. OF TASKS</th>
        <th>NO. OF EMPLOYEES</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @employee_tasks_data.each do |team_id, team_members_data| %>

      <tr>
        <td><%= team_id %></td>
        <td id="team-task-details" class="clickable-item"><%= link_to team_name(team_id),single_team_tasks_report_path(team_id: team_id), remote: true, class:"clickable-item" %></td>
        <td><%= team_department_name(team_id) %></td>
        <td><%= team_tasks_count(team_id) %></td>
        <td><%= team_employees_count(team_id) %></td>
        <td  class="d-table-cell align-middle vertical-align">
          <div class="row no-gutters justify-content-between">
            <div class="btn-group dropleft">
              <i class="fas fa-ellipsis-v cursor-pointer" title="More..." class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ></i>
              <div class="dropdown-menu">
                <%= link_to "Show Details",single_team_tasks_report_path(team_id: team_id), remote: true, class:"dropdown-item" %>
              </div>
            </div>
          </div>

        </td>
      </tr>
  <% end %>
    </tbody>

  </table>
</div>

<div id="task-details" class="container pagination-div">

</div>

app/views/reports/_velocity_report.html.erb
<% content_for :bread_crumbs do %>
  <div class="row d-flex p-1">
      <p class="m-0 align-middle">Employee Velocity Report</p>
  </div>
<% end %>
<% @employee_tasks_data.each do |team_id, team_members_data| %>
<div class="container velocity-report">
  <div class="col-md-10">
    <center>
      <h5><%= team_name(team_id) %></h5>
    </center>
  </div>

<div class="container table-responsive">
<table id="velocityreport_table" class="table data table-hover dt-responsive full-width">
  <thead>
    <tr>
      <th >ID</th>
      <th >NAME</th>
      <th >TOTAL TASKS</th>
      <th >AVG. COMPLEXITY</th>
      <th >AVG. TIME</th>
      <th >VELOCITY <br> (avg. complexity / avg. time)</th>
    </tr>
  </thead>
  <tbody>
      <% team_members_data.each do |employee_id, employee_velocity_data|  %>
        <tr>
          <td><%= employee_velocity_data[:employee_id] %></td>
          <td><%= employee_velocity_data[:employee_name].downcase.titleize %></td>
          <td><%= employee_velocity_data[:total_tasks] %></td>
          <td><%= employee_velocity_data[:total_complexity] %></td>
          <td><%= employee_velocity_data[:total_time] %></td>
          <td><%= employee_velocity(employee_velocity_data[:velocity]) %></td>
        </tr> 
    <% end %>
  </tbody>
</table>
</div>
<% end %>

app/views/reports/attendance_report.html.erb
<% content_for :bread_crumbs do %>
  <div class="row d-flex p-1">
      <p class="m-0 align-middle">Employee Attendance Report</p>
  </div>
<% end %>

<%= render 'attendance_report_grid'%>
<div>
<%= will_paginate @attendances, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
</div>

app/views/reports/employee_velocity_pdf_report.html.erb
<div class="container">
  <center>
    <h1>Employee Velocity Report</h1>
    <p>Printed by Employee: <%= current_employee.name %></p>
  </center>
</div>
<br>
<div class="container">
  <%= render 'velocity_report' %> 
</div>

app/views/reports/index.html.erb
<div class="accordion md-accordion" id="accordionEx" role="tablist" aria-multiselectable="true">
  <div class="card">
    <div class="card-header" role="tab" id="headingOne1">
      <a data-toggle="collapse" data-parent="#accordionEx" href="#collapseOne1" aria-expanded="true"
        aria-controls="collapseOne1">
        <p class="mb-0">
          Reports <i class="fas fa-angle-down rotate-icon float-right"></i>
        </p>
      </a>
    </div>
    <div id="collapseOne1" class="collapse show" role="tabpanel" aria-labelledby="headingOne1"
      data-parent="#accordionEx">
      <div class="card-body">
        <div>
          <%= link_to task_report_reports_path, class: "btn btn-secondary" do %>
            <i class="fa fa-tasks"></i> Task Report
          <% end %> 
          <%= link_to show_employee_velocity_report_path, class: "btn btn-secondary" do %>
            <i class="fa fa-line-chart"></i> Velocity Report
          <% end %>    
          <%= link_to attendance_report_path, class: "btn btn-secondary" do %>
            <i class="fa fa-tasks"></i> Attendance Report
          <% end %> 
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/load_task_data_in_report.js.erb
$('#tasks_table').html('')
$('#tasks_table').append("<%= j render 'reports/tasks_report_list' %>")

app/views/reports/show.html.erb
<% content_for :bread_crumbs do %>
  <div class="row d-flex p-1">
      <p class="m-0 align-middle">Employee pdf_velocity_report_path Report</p>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-10">
      <center>
        <h1>Employee Velocity Report</h1>
      </center>
    </div>
    <div class="col-2">
        <div class="align-content-right mr-0 pr-0 ml-report-btn">
        <%= link_to  pdf_velocity_report_path(format: :pdf), class: 'btn btn-regular', target: :_blank do %>
          Export pdf
          <i class="fas fa-file-pdf ml-2"></i>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <%= render 'teams_tasks_list' %>
  </div>
</div>

app/views/reports/single_team_tasks.js.erb
$('#task-details').html("<%=escape_javascript render(:partial => 'team_task_velocity') %>");

app/views/reports/task_pdf_report.html.erb
<div class="container datatable-container">
  <div>
    <%= render 'reports/tasks_report_list', tasks: @tasks %>
  </div> 
</div>

app/views/reports/task_report.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'filter' %>
<% end %>
<% content_for :bread_crumbs do %>
  <div class="row d-flex p-1">
      <p class="m-0 align-middle">Task Report</p>
  </div>
<% end %>
<div class="container">
  <%= form_tag(task_pdf_csv_report_reports_path, method: :get) do %>
    <div class="row d-flex">
      <div class="col-8"></div>
      <div class="col-4 d-flex">
        <button class="btn btn-regular" id="filter_btn" type="button" data-toggle="collapse" data-target="#multiCollapseFilter" aria-expanded="false" aria-controls="multiCollapseFilter"><i class="fas fa-angle-up d-none" id="up_arrow"></i><p class="m-0">Filter By</p></button>
        <button class="btn btn-regular ml-2" type="submit" name="pdf" target="_blank">Export pdf <i class="fas fa-file-pdf ml-2"></i></button>
        <button class="btn btn-regular ml-2" type="submit" name="csv">Export csv <i class="fas fa-file-csv ml-2"></i></button>
      </div>
      <div class="col">
        
      </div>
      <div class="col">
        
      </div>
    </div>
    <div class="collapse multi-collapse mt-2" id="multiCollapseFilter">  
      <div class="row">
        <div class="col">
          <b class="filter-text">Start Date Range</b>
        </div>
        <div class="col">
          <b class="filter-text">Expected End Date Range</b>
        </div>
      </div>
      <div class="row filter-line-height">
        <div class="col">
          <div class="row">
            <div class="col-6">
              <%= date_field_tag 'created_start', nil, class: 'form-control' %>
            </div>
            <div class="col-6">
              <%= date_field_tag 'created_end', nil, class: 'form-control' %>
            </div>
          </div>
          <div id="created_date_range error"></div>
        </div>
        <div class="col">
          <div class="row">
            <div class="col-6">
              <%= date_field_tag 'deadline_start', nil, class: 'form-control' %> 
            </div>
            <div class="col-6">
              <%= date_field_tag 'deadline_end', nil, class: 'form-control' %>
            </div>
          </div>
           <span id="deadline_date_range error"></span>
        </div>
      </div>
      <div class="row mt-0">
        <div class="col-3">
          <b class="filter-text">Project</b>
        </div>
        <div class="col-3">
          <b class="filter-text">Status</b>
        </div>
      </div>
      <div class="row">
        <div class="col-3">
          <%= text_field_tag 'project', nil, class: 'form-control' %>
        </div>
        <div class="col-3">
          <%= select_tag(:status, options_for_select([["--Choose Status--", ''], ["New", "New"], ["In Progress", "In Progress"], ["Review pending", "Review pending"], ["Reviewed", "Reviewed"], ["Completed", "Completed"]]),class: 'form-control') %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6"></div>
        <div class="col-md-6 btn-padding">
          <button class="btn btn-regular" type="button" id="update">Filter</button>&nbsp;
          <button class="btn btn-peach" type="button" id="clear">Clear</button>
        </div>
      </div>
    </div>
  <% end %>
  <br>
  <div id="tasks_tablee">
    <%= render 'reports/tasks_report_list', tasks: @tasks %>
  </div>
</div> 